package:
 name: transrate	
 version: "1.0.1"

source:
 fn: transrate-1.0.1.tar.gz
 url: https://bintray.com/blahah/generic/download_file?file_path=transrate-1.0.1-linux-x86_64.tar.gz
 sha1: 0f21017b52307f26b1d5e05583fb8bf081944281

about:
 home: https://github.com/blahah/transrate
 license: MIT
 license_file: LICENSE
 summary: transrate assebmly evaluation
